name: Simple.yml

on: [workflow_dispatch]

jobs:
  run-shell-command:
    name: run-shell-command-test-name
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"

      - name: multiline script
        run: |
          node -v
          npm -v

      - name: show directors (ls)
        run: ls -a

      - name: end of the job
        run: echo "--- End of the job!! ---"

  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: second job step one
        run: echo "second job step one"

  third-job:
    runs-on: ubuntu-latest
    steps:
      - name: Output some Job Summary
        run: echo '### It works!!! :rocket:' >> $GITHUB_STEP_SUMMARY

  fourth-job:
    runs-on: ubuntu-latest
    steps:
      - name: Use a composite action"
        uses: ./.github/test-action
        with:
          test_input: "Hello World Composite Action"
